version: '3.8'  # Use a more recent version of Docker Compose syntax
services:
  web:
    build: .
    ports:
      - '8080:80'  # Map host port 80 to container port 80 (as per app.py)
    depends_on:
      - redis  # Ensure Redis starts before the Flask app
  redis:
    image: 'redis:alpine'
    # image: 'redis:${WOW_URL}'

  db:
    image: "postgres"
    ports:
      - 8001:5432
    environment:
      - POSTGRES_PASSWORD=password